adapter: "mysql2"
pool: 15
host: "localhost"
encoding: "utf8"
username: "root"
database: "garderob"
password: ""
# password => "ctrhtnfhbfn",
# socket => "/var/run/mysqld/mysqld.sock"
socket: "/var/lib/mysql/mysql.sock"