shoes:
  id: 1
  name_en: Shoes
  name_ru: Туфли
  link: "http://6pm.com/shoes"
  active: true
clothing:
  id: 2
  name_en: Clothing
  name_ru: Одежда
  link: "http://www.6pm.com/clothing"
  active: false
bags:
  id: 3
  name_en: Bags
  name_ru: Сумки
  link: "http://www.6pm.com/bags"
  active: false
accessories:
  id: 4
  name_en: Accessories
  name_ru: Aксессуары
  link: "http://www.6pm.com/accessories"
  active: false